-- Hand-written data migration, not generated by drizzle-kit.
--
-- 0001 added lesson_progress.completions with a default of 0, but rows already
-- marked completed represent one completion. Left at 0, the next attempt would
-- be stamped as run 1 and join the original run, so a replay would be scored
-- against the first pass and would report XP it did not award.
UPDATE lesson_progress SET completions = 1 WHERE status = 'completed' AND completions = 0;
