import type { Unit } from '@fin/core';

/**
 * Renders the authored course into SQL that updates D1 in place.
 *
 * Content is upserted by id rather than deleted and re-inserted. Learner
 * progress references lessons and exercises with ON DELETE CASCADE, so the
 * earlier delete-everything seed wiped every attempt and lesson row on each
 * content update while leaving total XP behind. With the solved-exercise
 * history gone, every learner could then earn that XP again.
 *
 * Reordering needs care. Lessons are unique on (unit_id, sort_order) and
 * exercises on (lesson_id, sort_order), and SQLite checks those per row, so
 * swapping two lessons in place would briefly give both the same position.
 * Every existing row is first moved to -rowid, which is unique across the
 * table whatever state it was left in, and cannot collide with a final
 * position because final positions are never negative.
 *
 * Content removed from the source is deleted at the end, and that does cascade
 * to its attempts and lesson progress. That is correct for content that is
 * genuinely gone, but it also means renaming an id loses progress on it, since
 * a rename looks like one removal and one addition.
 */
export function renderSeedSql(units: Unit[], now: number): string {
  const lessons = units.flatMap((unit) => unit.lessons);
  const exercises = lessons.flatMap((lesson) => lesson.exercises);

  // An empty id list would turn the removal statements below into
  // "delete everything", so refuse rather than emit that.
  if (units.length === 0 || lessons.length === 0 || exercises.length === 0) {
    throw new Error(
      `Refusing to seed an incomplete course (${units.length} units, ` +
        `${lessons.length} lessons, ${exercises.length} exercises).`,
    );
  }

  const statements: string[] = [
    '-- Generated by apps/api/scripts/generate-seed.ts. Do not edit by hand.',
    '-- Upserts content in place so learner progress survives. See src/seed-sql.ts.',
    'UPDATE lessons SET sort_order = -rowid;',
    'UPDATE exercises SET sort_order = -rowid;',
  ];

  for (const unit of units) {
    statements.push(
      `INSERT INTO units (id, title, description, sort_order, created_at) VALUES (${values(
        unit.id,
        unit.title,
        unit.description,
        unit.order,
        now,
      )}) ON CONFLICT(id) DO UPDATE SET title = excluded.title, ` +
        'description = excluded.description, sort_order = excluded.sort_order;',
    );
  }

  // Prerequisites carry no progress, so replacing them wholesale is safe. They
  // go after every unit exists, since a unit may depend on one declared later.
  statements.push('DELETE FROM unit_prerequisites;');
  for (const unit of units) {
    for (const prerequisite of unit.prerequisites) {
      statements.push(
        `INSERT INTO unit_prerequisites (unit_id, prerequisite_unit_id) VALUES (${values(
          unit.id,
          prerequisite,
        )});`,
      );
    }
  }

  for (const unit of units) {
    unit.lessons.forEach((lesson, lessonIndex) => {
      statements.push(
        `INSERT INTO lessons (id, unit_id, title, intro, sort_order) VALUES (${values(
          lesson.id,
          unit.id,
          lesson.title,
          lesson.intro ?? null,
          lessonIndex,
        )}) ON CONFLICT(id) DO UPDATE SET unit_id = excluded.unit_id, title = excluded.title, ` +
          'intro = excluded.intro, sort_order = excluded.sort_order;',
      );
    });
  }

  for (const lesson of lessons) {
    lesson.exercises.forEach((exercise, exerciseIndex) => {
      statements.push(
        `INSERT INTO exercises (id, lesson_id, kind, prompt, explanation, sort_order, payload) VALUES (${values(
          exercise.id,
          lesson.id,
          exercise.kind,
          exercise.prompt,
          exercise.explanation ?? null,
          exerciseIndex,
          JSON.stringify(exercise),
        )}) ON CONFLICT(id) DO UPDATE SET lesson_id = excluded.lesson_id, kind = excluded.kind, ` +
          'prompt = excluded.prompt, explanation = excluded.explanation, ' +
          'sort_order = excluded.sort_order, payload = excluded.payload;',
      );
    });
  }

  statements.push(
    `DELETE FROM exercises WHERE id NOT IN (${values(...exercises.map((e) => e.id))});`,
    `DELETE FROM lessons WHERE id NOT IN (${values(...lessons.map((l) => l.id))});`,
    `DELETE FROM units WHERE id NOT IN (${values(...units.map((u) => u.id))});`,
  );

  return `${statements.join('\n')}\n`;
}

function values(...items: (string | number | null)[]): string {
  return items.map(quote).join(', ');
}

function quote(value: string | number | null): string {
  if (value === null) return 'NULL';
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) throw new Error(`Cannot write non-finite number ${value}`);
    return String(value);
  }
  return `'${value.replace(/'/g, "''")}'`;
}
