#!/usr/bin/env node
/**
 * One-command local bootstrap: `pnpm setup:local`.
 *
 * Named setup:local rather than setup because `pnpm setup` is a built-in
 * pnpm command and would shadow this entirely.
 *
 * Writes the git-ignored env files with a secret generated on this machine,
 * then migrates and seeds the local D1 database. Nothing here touches
 * Cloudflare, so a new contributor needs no account to run the app.
 *
 * Safe to re-run: existing env files are left alone.
 */
import { randomBytes } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { existsSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(dirname(fileURLToPath(import.meta.url)));

const REQUIRED_NODE_MAJOR = 22;

function checkNode() {
  const major = Number(process.versions.node.split('.')[0]);
  if (major < REQUIRED_NODE_MAJOR) {
    fail(
      `Node ${process.versions.node} is too old. Wrangler needs ${REQUIRED_NODE_MAJOR}+.\n` +
        `  nvm use   (this repo pins a version in .nvmrc)`,
    );
  }
  step(`Node ${process.versions.node}`);
}

function writeIfMissing(relativePath, contents, description) {
  const path = join(root, relativePath);

  if (existsSync(path)) {
    step(`${relativePath} already exists, left alone`);
    return;
  }

  writeFileSync(path, contents, { mode: 0o600 });
  step(`wrote ${relativePath} (${description})`);
}

function run(command, args, cwd) {
  execFileSync(command, args, { cwd: join(root, cwd), stdio: 'inherit' });
}

function step(message) {
  console.log(`  ${message}`);
}

function fail(message) {
  console.error(`\nSetup failed: ${message}\n`);
  process.exit(1);
}

console.log('\nSetting up local development\n');

checkNode();

// A secret generated here never leaves this machine and is never committed.
// Each contributor gets their own; there is nothing to share or copy.
writeIfMissing(
  'apps/api/.dev.vars',
  [
    '# Generated by `pnpm setup:local`. Git-ignored. Local only.',
    `BETTER_AUTH_SECRET="${randomBytes(32).toString('base64')}"`,
    'BETTER_AUTH_URL="http://localhost:8787"',
    'TRUSTED_ORIGINS="http://localhost:8081,http://localhost:8787,fineduapp://"',
    '',
  ].join('\n'),
  'includes a freshly generated secret',
);

writeIfMissing(
  'apps/mobile/.env.local',
  [
    '# Generated by `pnpm setup:local`. Git-ignored.',
    '# On a physical device use your machine LAN IP instead of localhost.',
    'EXPO_PUBLIC_API_URL=http://localhost:8787',
    '',
  ].join('\n'),
  'points the client at the local API',
);

console.log('\nPreparing the local database\n');

try {
  run('npx', ['wrangler', 'd1', 'migrations', 'apply', 'fin-edu-db', '--local'], 'apps/api');
  run('pnpm', ['db:seed:local'], 'apps/api');
} catch {
  fail('database setup did not complete. Fix the error above and re-run `pnpm setup:local`.');
}

console.log('\nReady. Run the two halves in separate terminals:\n');
console.log('  pnpm dev:api      http://localhost:8787');
console.log('  pnpm dev:mobile   press w for web\n');
