import { mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { units } from '@fin/content';

/**
 * Renders the authored course in @fin/content into a SQL file that wrangler
 * applies to D1. Content is fully replaced on each run, so seeding is
 * idempotent and a lesson removed from the source disappears from the database.
 *
 * Learner progress is untouched: deleting a unit cascades to its lessons and
 * exercises, which cascades to progress rows referencing them, so only remove
 * content deliberately.
 *
 *   pnpm --filter @fin/api db:seed:local
 */

const outputPath = resolve(dirname(fileURLToPath(import.meta.url)), '../.seed/content.sql');

function quote(value: string | number | null): string {
  if (value === null) return 'NULL';
  if (typeof value === 'number') return String(value);
  return `'${value.replace(/'/g, "''")}'`;
}

const statements: string[] = [
  '-- Generated by apps/api/scripts/generate-seed.ts. Do not edit by hand.',
  'PRAGMA defer_foreign_keys = true;',
  'DELETE FROM exercises;',
  'DELETE FROM lessons;',
  'DELETE FROM unit_prerequisites;',
  'DELETE FROM units;',
];

const now = Math.floor(Date.now() / 1000);

for (const unit of units) {
  statements.push(
    `INSERT INTO units (id, title, description, sort_order, created_at) VALUES (${[
      quote(unit.id),
      quote(unit.title),
      quote(unit.description),
      unit.order,
      now,
    ].join(', ')});`,
  );

  for (const prerequisite of unit.prerequisites) {
    statements.push(
      `INSERT INTO unit_prerequisites (unit_id, prerequisite_unit_id) VALUES (${quote(unit.id)}, ${quote(prerequisite)});`,
    );
  }

  unit.lessons.forEach((lesson, lessonIndex) => {
    statements.push(
      `INSERT INTO lessons (id, unit_id, title, intro, sort_order) VALUES (${[
        quote(lesson.id),
        quote(unit.id),
        quote(lesson.title),
        quote(lesson.intro ?? null),
        lessonIndex,
      ].join(', ')});`,
    );

    lesson.exercises.forEach((exercise, exerciseIndex) => {
      statements.push(
        `INSERT INTO exercises (id, lesson_id, kind, prompt, explanation, sort_order, payload) VALUES (${[
          quote(exercise.id),
          quote(lesson.id),
          quote(exercise.kind),
          quote(exercise.prompt),
          quote(exercise.explanation ?? null),
          exerciseIndex,
          quote(JSON.stringify(exercise)),
        ].join(', ')});`,
      );
    });
  });
}

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, `${statements.join('\n')}\n`, 'utf8');

const lessonCount = units.reduce((total, unit) => total + unit.lessons.length, 0);
const exerciseCount = units.reduce(
  (total, unit) => total + unit.lessons.reduce((sum, lesson) => sum + lesson.exercises.length, 0),
  0,
);

console.log(
  `Wrote ${outputPath}\n  ${units.length} units, ${lessonCount} lessons, ${exerciseCount} exercises`,
);
